export const ExpenseCategory = {
    FOOD: "Food",
    TRAVEL: "Travel",
    ENTERTAINMENT: "Entertainment",
    GROCERY: "Grocery",
    OTHERS: "Others",
    MEDICAL: "Medical",
    EDUCATION: "Education",
    BILLS: "Bills",
    SHOPPING: "Shopping",
    TRANSPORTATION: "Transportation",
    PERSONAL: "Personal",
    HOME: "Home",
    INVESTMENT: "Investment",
    INSURANCE: "Insurance",
    CHARITY: "Charity",
    TAXES: "Taxes",
    GIFTS: "Gifts",
    SAVINGS: "Savings",
    CLOTHING: "Clothing",
};